#!/bin/bash
source ~/.jsenv.sh
cd $CODEDIR/github/jumpscale/developer/scripts9

set +ex
echo '* remove dockers'
docker rm -f -v $(sudo docker ps -a -q) > /dev/null 2>&1
echo '* remove docker images'
docker rmi -f $(docker images -q) > /dev/null 2>&1
