#!/bin/bash
source ~/.jsenv.sh


function linkcmds {
    if [ -z "$iname" ]; then
        if [ -z "$CODEDIR" ]; then
            echo "Please define name of docker instance by setting variable: iname"
            exit 1
        fi
        #link all our command lines relevant to jumpscale development env
        rm -f /usr/local/bin/js9*
        rm -rf /usr/local/bin/cmds*
        if [ -e /root/.iscontainer ]; then
            #we are in container
            echo "* link commands to container"
            set -x
            find  $CODEDIR/github/jumpscale/core9/cmds -exec ln -s {} "/usr/local/bin/" \;
            rm -rf /usr/local/bin/cmds
            find  $CODEDIR/github/jumpscale/developer/cmds_guest -exec ln -s {} "/usr/local/bin/" \;
            rm -rf /usr/local/bin/cmds_guest
        else
            echo "* link commands to local environment"
            find  $CODEDIR/github/jumpscale/developer/cmds_host -exec ln -s {} "/usr/local/bin/" \;
            rm -rf /usr/local/bin/cmds_host
        fi
    else
        echo "* link commands to container"
        docker exec -t $iname bash -c 'source /root/.jsenv.sh;source $CODEDIR/github/jumpscale/core9/cmds/js9_base;linkcmds' > /tmp/lastcommandoutput.txt 2>&1
    fi

}


linkcmds > /tmp/lastcommandoutput.txt 2>&1
